# Install script for directory: /home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

IF(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0001/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0002/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0003/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0004/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0005/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0006/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0007/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0008/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0009/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0010/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0011/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0012/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0013/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0014/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0015/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0016/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0017/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0018/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0019/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0020/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0021/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0022/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0023/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0024/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0025/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0026/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0027/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0028/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0029/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0030/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0031/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0032/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0033/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0034/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0035/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0036/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0037/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0038/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0039/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0040/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0041/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0042/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0043/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0044/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0045/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0046/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0047/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0048/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0049/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0050/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0051/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0052/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0053/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0054/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0055/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0056/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0057/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0058/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0059/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0060/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0061/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0062/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0063/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0064/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0065/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0066/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0067/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0068/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0069/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0070/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0071/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0072/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0073/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0074/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0075/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0076/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0077/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0078/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0079/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0080/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0081/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0082/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0083/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0084/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0085/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0086/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0087/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0088/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0089/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0090/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0091/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0092/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0093/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0094/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0095/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0096/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0097/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0098/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0099/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0100/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0101/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0102/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0103/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0104/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0105/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0106/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0107/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0108/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0109/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0110/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0111/cmake_install.cmake")
  INCLUDE("/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/eu0112/cmake_install.cmake")

ENDIF(NOT CMAKE_INSTALL_LOCAL_ONLY)

IF(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
ELSE(CMAKE_INSTALL_COMPONENT)
  SET(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
ENDIF(CMAKE_INSTALL_COMPONENT)

FILE(WRITE "/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/${CMAKE_INSTALL_MANIFEST}" "")
FOREACH(file ${CMAKE_INSTALL_MANIFEST_FILES})
  FILE(APPEND "/home/melquiades/aLab/99_Personal/01_EulerProject/eulerProject/bin_old/${CMAKE_INSTALL_MANIFEST}" "${file}\n")
ENDFOREACH(file)
